{
"name": "Detective Conan THE Movie",
"author": "สถานีความบันเทิงส่วนตัว",
"image": "https://i.pinimg.com/originals/4a/ad/f3/4aadf3135705585b4ce8d5a31f13496c.gif",
"url": "",
"stations": [

{"name":"Detective Conan Movie 1 : The Time-Bombed Skyscraper คดีปริศนาระเบิดระฟ้า","image":"https://ais-s.ais-vidnt.com/ais/play/origin/VOD/Poster/ais-06wIR1-DBM8c.87481402.poster.HD.jpg",
"url": "https://www.animetobi.com/embed/39705/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 2 : The Fourteenth Target คดีฆาตกรรมไพ่ปริศนา","image":"https://ais-s.ais-vidnt.com/ais/play/origin/VOD/Poster/ais-u6wIR1-uPM8c.87481502.poster.SD.jpg",
"url": "https://www.animetobi.com/embed/39706/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 3 : The Last Wizard of the Century ปริศนาพ่อมดคนสุดท้ายแห่งศตวรรษ","image":"https://www.themoviedb.org/t/p/original/qwWtCv92kuNSnTJQk1DeyqrbmFu.jpg",
"url": "https://www.animetobi.com/embed/39707/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 4 : Captured in Her Eyes คดีฆาตกรรมนัยน์ตามรณะ","image":"https://ais-s.ais-vidnt.com/ais/play/origin/VOD/Poster/ais-vFXIR1-H9N8c.87484452.poster.HD.jpg",
"url": "https://www.animetobi.com/embed/39708/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 5 : Countdown to Heaven คดีปริศนาเส้นตายสู่สวรรค์","image":"https://movie2z-hd.com/imgmovie/120212.jpg",
"url": "https://www.animetobi.com/embed/39709/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 6 : The Phantom of Baker Street ปริศนาบนถนนสายมรณะ","image":"https://www.themoviedb.org/t/p/w500/5wvXPrH6CaW0TYZ84bNekcM1ZFF.jpg",
"url": "https://www.animetobi.com/embed/39710/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 7 : Crossroad in the Ancient Capital คดีฆาตกรรมแห่งเมืองปริศนา","image":"http://www.lib.buu.ac.th/av/dvd/images/dvd2426.jpg",
"url": "https://www.animetobi.com/embed/39711/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 8 : Magician of the Silver Sky มนตราแห่งรัตติกาลสีเงิน","image":"https://ais-s.ais-vidnt.com/ais/play/origin/VOD/Poster/ais-mrKIR1-EuN8c.87484702.poster.original.jpg",
"url": "https://www.animetobi.com/embed/39712/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 9 : Strategy Above the Depths ยุทธการเหนือห้วงทะเลลึก","image":"https://ais-s.ais-vidnt.com/ais/play/origin/VOD/Poster/ais-fxKIR1-LxN8c.87491152.poster.original.jpg",
"url": "https://www.animetobi.com/embed/39713/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 10 : The Private Eyes&#39; Requiem บทเพลงมรณะแด่เหล่านักสืบ","image":"https://i0.wp.com/yummovie.com/wp-content/uploads/2019/12/paRjoAuHmdexVOB2npVdz3OoSUQ.jpg?fit=500%2C750&ssl=1",
"url": "https://www.animetobi.com/embed/43183/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 11 : Jolly Roger in the Deep Azure ปริศนามหาขุมทรัพย์โจรสลัด","image":"https://ais-s.ais-vidnt.com/ais/play/origin/VOD/Poster/ais-LQAIR1-bLM8c.87481652.poster.HD.jpg",
"url": "https://www.animetobi.com/embed/39714/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 12 : Full Score of Fear บทบรรเลงแห่งความตาย","image":"https://upload.wikimedia.org/wikipedia/th/6/6a/Full_Score_Of_Fear.jpg",
"url": "https://www.animetobi.com/embed/39715/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 13 : The Raven Chaser ปริศนานักล่าทรชนทมิฬ","image":"https://ais-s.ais-vidnt.com/ais/play/origin/VOD/Poster/ais-0NAIR1-CZM8c.87481902.poster.HD.jpg",
"url": "https://www.animetobi.com/embed/39716/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 14 : The Lost Ship In The Sky ปริศนามรณะเหนือน่านฟ้า","image":"https://upload.wikimedia.org/wikipedia/th/c/c4/The_Lost_Ship_in_the_Sky_Poster.jpg",
"url": "https://www.animetobi.com/embed/39717/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 15 : Quarter of Silence 15 นาทีเฉียดวิกฤติมรณะ","image":"https://ais-s.ais-vidnt.com/ais/play/origin/VOD/Poster/ais-ayVIR1-G7N8c.87482102.poster.original.jpg",
"url": "https://www.animetobi.com/embed/39718/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 16 : The Eleventh Striker ปริศนาระทึก-ศึกลูกหนังมรณะ","image":"https://www.themoviedb.org/t/p/original/makUKhrs7YkPPwLydEaU3Q2oaCN.jpg",
"url": "https://www.animetobi.com/embed/39719/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 17 : Private Eye in the Distant Sea ฝ่าวิกฤติเรือรบมรณะ","image":"https://upload.wikimedia.org/wikipedia/th/5/51/%E0%B8%9D%E0%B9%88%E0%B8%B2%E0%B8%A7%E0%B8%B4%E0%B8%81%E0%B8%A4%E0%B8%95%E0%B8%B4%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B8%A3%E0%B8%9A%E0%B8%A1%E0%B8%A3%E0%B8%93%E0%B8%B0.jpg",
"url": "https://www.animetobi.com/embed/39720/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 18 : Dimensional Sniper ปริศนากระสุนมรณะ","image":"https://ais-s.ais-vidnt.com/ais/play/origin/VOD/Poster/ais-tlsUP1-r8sc.1880251.poster.original.jpg",
"url": "https://www.animetobi.com/embed/39721/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 19 : Sunflowers of Inferno ปริศนาทานตะวันมรณะ","image":"https://upload.wikimedia.org/wikipedia/th/thumb/1/1e/%E0%B8%9B%E0%B8%A3%E0%B8%B4%E0%B8%A8%E0%B8%99%E0%B8%B2%E0%B8%97%E0%B8%B2%E0%B8%99%E0%B8%95%E0%B8%B0%E0%B8%A7%E0%B8%B1%E0%B8%99%E0%B8%A1%E0%B8%A3%E0%B8%93%E0%B8%B0.jpg/640px-%E0%B8%9B%E0%B8%A3%E0%B8%B4%E0%B8%A8%E0%B8%99%E0%B8%B2%E0%B8%97%E0%B8%B2%E0%B8%99%E0%B8%95%E0%B8%B0%E0%B8%A7%E0%B8%B1%E0%B8%99%E0%B8%A1%E0%B8%A3%E0%B8%93%E0%B8%B0.jpg",
"url": "https://www.animetobi.com/embed/39722/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 20 : The Darkest Nightmare ปริศนารัตติกาลทมิฬ","image":"https://th-test-11.slatic.net/p/6105bec26f1e92d81437a2b201129e84.jpg",
"url": "https://www.animetobi.com/embed/39723/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 21 : The Crimson Love Letter ปริศนาเพลงกลอนซ่อนรัก","image":"https://th-test-11.slatic.net/p/86582de752d451da683432edac834aec.jpg",
"url": "https://www.animetobi.com/embed/39724/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 22 : Zero the Enforcer ปฏิบัติการสายลับเดอะซีโร่","image":"https://lzd-img-global.slatic.net/g/p/9dd00473580efebf8a193d7d01f7c5b7.jpg_720x720q80.jpg_.webp",
"url": "https://www.animetobi.com/embed/39725/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan Movie 23 : The Fist of Blue Sapphire ศึกชิงอัญมณีสีคราม","image":"https://www.amornmovie.com/productimg.php?src=YTozOntzOjI6ImlkIjtzOjEwOiJBQUEwMDUyNDk3IjtzOjc6InNlY3Rpb24iO3M6NToiZnJvbnQiO3M6MzoiZGlyIjtzOjE6ImgiO30=",
"url": "https://www.animetobi.com/embed/39726/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan The Movie 24 The Scarlet Bullet (2021) ยอดนักสืบจิ๋วโคนัน กระสุนสีเพลิง","image":"https://cdn.majorcineplex.com/uploads/movie/3204/thumb_3204.jpg",
"url": "https://www.animetobi.com/embed/49861/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},
{"name":"Detective Conan The Scarlet Alibi (2021) ยอดนักสืบจิ๋วโคนัน ผ่าปริศนาปมมรณะ เดอะมูฟวี่ พากย์ไทย","image":"https://www.jiggaban.com/wp-content/uploads/2021/03/AED51EF8-4C8E-4556-996F-111737D29415-390x555.jpeg",
"url": "https://www.animetobi.com/embed/43831/",
"playInNatPlayer": "true","referer": "https://www.animetobi.com/"},]},
